language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libtool
    - libglib2.0-dev
    - libjson-c-dev
    - libcurl4-openssl-dev
    - gnome-common
    - libnotify-dev
    - libgtk-3-dev
    - libappindicator3-dev
  coverity_scan:
    project:
      name: armadito/armadito-systray-ui
      description: Build submitted via Travis CI
    notification_email: vhamon@teclib.com
    build_command_prepend: "./configure; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
  sonarqube: true

env:
  global:
  - secure: "Xfme6eQPH3TU6AwP0Jbqu8n43hOtUm0rEOCA+HcP5YZZ9dL0rC7RAE5WXTMQG7X127r6YX+foJubfdrPfeQ6L3z4bthkjsJylphmiKPKdpVEq42T5N/wgJpzbW5Uie0U9PeXtZB+UJKwgZM7xJOiI799U5LImQvBTML/TJ7T3SZ23/WH152uZ2hzdX9CKWR38xcFIV89FzLzhAP6Taq6PY5Z/hnvPtkLa2zuF5WjknLHvt38nieyBdRUv5z/ZJl/3qA2UbI6yqP1F5m7jk59DN8MB5OggkrvUss+iYhnZh64pky/D+IESEdTbZC0DaLOxwX8kSSmARQTIodA00qmDuIJ8c4ciyCww+QJa6Z2Tngz1khsQUBJe+C/Exlu/LKUpWkjVzrKCgUJ+pDMlTSzK0qcpXftoQG0Oha0tPvFdbqTD6G5faOGvAxjsNrcZkD83d1ZFXdAaVAAbKVGMOG9BZTHcjWjAMpCL+z7xg95s3mE+7z5+BdzfQHHSCGUclt4xn9N3xx5GTCvjypy1r13u1peBIu5gR4MoC3n2PlKFjDn75PwXvXTRf7ijax/pkfgRYLIiqDozv1Bsc9Qb0WDSGWatanyWYXVGKK2e/tSKth+yVr3JMeSYWNk7mC8J21tO/pYzdTypryv0qi05M32pNad6IlElA9EuMq6AS+2OcA="
  - secure: "blMEmG81NnwBaasGjgb6yXS4d7sBQ1Z7pXUT9NvllnbHFG0BArsWi5S4wNfRZGeD+GFx/A3cmRswcgCZJ+jO6bNzHx6yuU9gpje9Fg5a6mocW8MYxd9A80B77fgQN630eYElNBN1f19uuGpHc53wE5bXdP5u4Hpl4hT9NBtBVwLDQcBeRm/Etw4evfIkv/kavL3EHtviZUkORoZQ8LGhaka57LjoCe5h6E2O3faTLWN6nCCr4pHh2xEva6APndpRm/dOTHpjGBl4MqydPOdmhcpppNGV1K6CS+PsMjLIBIZVCBf63zpGWlHf0wi5VLMTH/TWF4+hrTshLRbylnVkx5MQrVfctCLK51NR164onZ9WA8Fn+wDYDIRWfFgNpz985mxMQ61rdbiCzwwsmd3vCEac6yUyQe13SWda0oavby254dV+mb8KGZZCt5zwYw7dMBfJ1S/gNPU85u+AApiHy/SwaqzgZUAwhpvCvOeS5zhQu9CjGDCw2EOTx/gXFfHiQp8HvxRDM/QS2k5tpszHGsZD4SM3zRJew28IlEM1N7J/WwFcgOD3z5wLd7qbXfHGSJiINWMLhuc6dtiLV9MYTuGbCkMcpSmQfSGNLzG/Apoiet9FE+2gpvR/kzwsEePvQEnCuyyZiz3Q53fFxGXfpCC4quMeQvl9q+kS1q8rfno="

before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

compiler:
- gcc

before_script:
- cd gtk
- "./autogen.sh"

script:
- ./configure
- make clean all
- cd ../
- sonar-scanner -e -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
